'use strict';

window.bgmpGdpr = {
	/**
	 * Detect the cookie set by the BlueConic GDPR opt-out prompt to opt out of
	 * certain tracking codes.
	 *
	 * You can add something like the following code surrounding javascript
	 * tracking scripts to short-circuit them if the current user is opted out
	 *
	 * Note: the if logic example below will cause tracker scripts that follow
	 * to be disabled if this plugin is deactivated or the window.bgmpGdpr object
	 * is undefined. Tweak as required for your own specific use cases, but this
	 * is most likely the safest approach to ensuring we don't track anyone
	 * who may have previously opted out, but we can't currently determine the
	 * state of the opt-out cookie.
	 *
	 * (function() {
	 *   if ( !window.bgmpGdpr || window.bgmpGdpr.isOptedOut() ) {
	 *     // Opt out cookie is set, don't continue on to tracking init logic
	 *     // below.
	 *     return;
	 *   }
	 *
	 *   // Tracking code init logic starts here...
	 * })();
	 */
	isOptedOut: function() {
		if ( document.cookie.split( ';' ).filter( function( item ) {
			return item.indexOf( 'bcNoCookieConsent=true' ) >= 0;
		} ).length ) {
			return true;
		}

		return false;
	},
	/**
	 * Listens for a click on the BlueConic Dialogue "No thanks" button
	 * and sets a cookie so that we remember the current user opted out on
	 * subsequent page loads.
	 */
	doOptOut: function( event ) {
		// Let's first make sure this click event was generated by a button with
		// the class .bcpConsentCancelButton (i.e. the BlueConic Dialogue markup
		// should add this class to the button that is the "I do not consent" to
		// be tracked opt-out action.
		if ( 'string' !== typeof event.target.className || -1 === event.target.className.split( ' ' ).indexOf( 'bcpConsentCancelButton' ) ) {
			// Don't do anything yet since we caught a click on an element that is not
			// our BlueConic opt out button (i.e. it doesn't have the
			// .bcpConsentCancelButton class).
			return;
		}

		// We detected a BlueConic Dialogue opt-out button click.
		// Set the opt-out cookie for 1 year.
		document.cookie = 'bcNoCookieConsent=true;path=/;max-age=31536000';
	},
	/**
	 * Listens for a click on the BlueConic Dialogue "Accept" button
	 * and sets a cookie so that we remember the current user opted in on
	 * subsequent page loads.
	 */
	doOptIn: function( event ) {
		if ( 'string' !== typeof event.target.className || -1 === event.target.className.split( ' ' ).indexOf( 'bcpConsentOKButton' ) ) {
			return;
		}

		// We detected a BlueConic Dialogue opt-out button click.
		// Set the opt-in cookie for 1 year.
		document.cookie = 'bcNoCookieConsent=false;path=/;max-age=31536000';
	},
	/**
	 * Deletes the bcNoCookieConsent cookie and forces a reload of the current
	 * page so that BlueConic re-presents the GDPR consent Dialogue.
	 */
	doReconfirmation: function( event ) {
		event.preventDefault();

		document.cookie = 'bcNoCookieConsent=false;path=/;max-age=0';

		window.location.reload( true );
	},
	/**
	 * Initialize event handlers.
	 */
	init: function() {
		// Setup delegated event handlers for BlueConic Dialogue button clicks.
		// Some help via: https://stackoverflow.com/a/27373951
		document.addEventListener( 'click', window.bgmpGdpr.doOptOut, false );
		document.addEventListener( 'click', window.bgmpGdpr.doOptIn, false );

		// Attempt to setup click handlers for .bgmp-gdpr-reconfirm hyperlinks.
		// For example: <a href="#" class="bgmp-gdpr-reconfirm">Click here to update your consent</a>
		var reconfirmLinks = document.getElementsByClassName( 'bgmp-gdpr-reconfirm' );

		for ( var i = 0; i < reconfirmLinks.length; i++ ) {
			reconfirmLinks[i].addEventListener( 'click', window.bgmpGdpr.doReconfirmation );
		}
	}
};

document.addEventListener( 'DOMContentLoaded', window.bgmpGdpr.init );
